# 1. Import the NUMPY package under the name np.

In [9]:
import numpy as np


## 2. Print the NUMPY version and the configuration.


## 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [10]:
a = np.random.random((2,3,5))


## 4. Print a.

In [11]:
print(a)

[[[0.83488086 0.12402801 0.13897497 0.65918294 0.48946481]
  [0.74546258 0.88790975 0.07386943 0.78078028 0.44175725]
  [0.66805433 0.52910382 0.96122587 0.38138914 0.84016676]]

 [[0.46772517 0.68367314 0.10056435 0.92988601 0.77962539]
  [0.77974264 0.66787911 0.88848443 0.43148744 0.29043451]
  [0.06177832 0.05462096 0.75861616 0.32316856 0.96089571]]]


## 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [12]:
b = np.ones((5,2,3))

## 6. Print b.

In [13]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 7. Do a and b have the same size? How do you prove that in Python code?

In [14]:
a.shape == b.shape

False

## 8. Are you able to add a and b? Why or why not?

In [16]:
#No, you're not. 

## 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [17]:
c = np.array(b).reshape(2,3,5)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

## 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [18]:
d = a + c
print(d)
#because a and c have the same dimensions. 

[[[1.83488086 1.12402801 1.13897497 1.65918294 1.48946481]
  [1.74546258 1.88790975 1.07386943 1.78078028 1.44175725]
  [1.66805433 1.52910382 1.96122587 1.38138914 1.84016676]]

 [[1.46772517 1.68367314 1.10056435 1.92988601 1.77962539]
  [1.77974264 1.66787911 1.88848443 1.43148744 1.29043451]
  [1.06177832 1.05462096 1.75861616 1.32316856 1.96089571]]]


## 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [19]:
print(a)
print(d)
#In ex. 10. we added the rearranged b (which we called C) to a, so we added 1 to all elements in a. 

[[[0.83488086 0.12402801 0.13897497 0.65918294 0.48946481]
  [0.74546258 0.88790975 0.07386943 0.78078028 0.44175725]
  [0.66805433 0.52910382 0.96122587 0.38138914 0.84016676]]

 [[0.46772517 0.68367314 0.10056435 0.92988601 0.77962539]
  [0.77974264 0.66787911 0.88848443 0.43148744 0.29043451]
  [0.06177832 0.05462096 0.75861616 0.32316856 0.96089571]]]
[[[1.83488086 1.12402801 1.13897497 1.65918294 1.48946481]
  [1.74546258 1.88790975 1.07386943 1.78078028 1.44175725]
  [1.66805433 1.52910382 1.96122587 1.38138914 1.84016676]]

 [[1.46772517 1.68367314 1.10056435 1.92988601 1.77962539]
  [1.77974264 1.66787911 1.88848443 1.43148744 1.29043451]
  [1.06177832 1.05462096 1.75861616 1.32316856 1.96089571]]]


## 12. Multiply a and c. Assign the result to e.

In [20]:
e = a * c
print(e)

[[[0.83488086 0.12402801 0.13897497 0.65918294 0.48946481]
  [0.74546258 0.88790975 0.07386943 0.78078028 0.44175725]
  [0.66805433 0.52910382 0.96122587 0.38138914 0.84016676]]

 [[0.46772517 0.68367314 0.10056435 0.92988601 0.77962539]
  [0.77974264 0.66787911 0.88848443 0.43148744 0.29043451]
  [0.06177832 0.05462096 0.75861616 0.32316856 0.96089571]]]


## 13. Does e equal to a? Why or why not?

In [21]:
#yes, it does. Because you are multiplying all values in a by 1. 

## 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [27]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9612258709644834


## 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [ ]:
f.array()
