# 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np


## 2. Print the NUMPY version and the configuration.


## 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [30]:
a = np.random.random((2,3,5))


## 4. Print a.

In [14]:
print(a)

[[[0.06523791 0.78938953 0.08795576 0.30958237 0.52995214]
  [0.58190463 0.58888508 0.82863747 0.51260685 0.48835282]
  [0.72537681 0.42479873 0.3113512  0.25002858 0.19384176]]

 [[0.06463913 0.26426542 0.11894184 0.5212192  0.52196466]
  [0.42909716 0.42317597 0.09982121 0.3447752  0.68964267]
  [0.09628478 0.74561513 0.58656919 0.76038344 0.67644806]]]


## 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [8]:
b = np.ones((5,2,3))

## 6. Print b.

In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 7. Do a and b have the same size? How do you prove that in Python code?

In [10]:
a.shape == b.shape

False

## 8. Are you able to add a and b? Why or why not?

In [ ]:
No, you're not. 

## 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [18]:
c = np.array(b).reshape(2,3,5)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [21]:
d = a + c
print(d)
#because a and c have the same dimensions. 

[[[1.06523791 1.78938953 1.08795576 1.30958237 1.52995214]
  [1.58190463 1.58888508 1.82863747 1.51260685 1.48835282]
  [1.72537681 1.42479873 1.3113512  1.25002858 1.19384176]]

 [[1.06463913 1.26426542 1.11894184 1.5212192  1.52196466]
  [1.42909716 1.42317597 1.09982121 1.3447752  1.68964267]
  [1.09628478 1.74561513 1.58656919 1.76038344 1.67644806]]]


## 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [23]:
print(a)
print(d)
#In ex. 10. we added the rearranged b (which we called C) to a, so we added 1 to all elements in a. 

[[[0.06523791 0.78938953 0.08795576 0.30958237 0.52995214]
  [0.58190463 0.58888508 0.82863747 0.51260685 0.48835282]
  [0.72537681 0.42479873 0.3113512  0.25002858 0.19384176]]

 [[0.06463913 0.26426542 0.11894184 0.5212192  0.52196466]
  [0.42909716 0.42317597 0.09982121 0.3447752  0.68964267]
  [0.09628478 0.74561513 0.58656919 0.76038344 0.67644806]]]
[[[1.06523791 1.78938953 1.08795576 1.30958237 1.52995214]
  [1.58190463 1.58888508 1.82863747 1.51260685 1.48835282]
  [1.72537681 1.42479873 1.3113512  1.25002858 1.19384176]]

 [[1.06463913 1.26426542 1.11894184 1.5212192  1.52196466]
  [1.42909716 1.42317597 1.09982121 1.3447752  1.68964267]
  [1.09628478 1.74561513 1.58656919 1.76038344 1.67644806]]]


## 12. Multiply a and c. Assign the result to e.

In [27]:
e = a * c
print(e)

[[[0.06523791 0.78938953 0.08795576 0.30958237 0.52995214]
  [0.58190463 0.58888508 0.82863747 0.51260685 0.48835282]
  [0.72537681 0.42479873 0.3113512  0.25002858 0.19384176]]

 [[0.06463913 0.26426542 0.11894184 0.5212192  0.52196466]
  [0.42909716 0.42317597 0.09982121 0.3447752  0.68964267]
  [0.09628478 0.74561513 0.58656919 0.76038344 0.67644806]]]


## 13. Does e equal to a? Why or why not?

In [28]:
#yes, it does. Because you are multiplying all values in a by 1. 

## 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"