# 1. Import the NUMPY package under the name np.

In [6]:
import numpy as np



## 2. Print the NUMPY version and the configuration.


In [7]:
print(np.version.version)


1.17.3


## 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [8]:
a = np.random.random((2,3,5))


## 4. Print a.

In [9]:
print(a)

[[[0.45308254 0.03322241 0.39584096 0.92154178 0.7553551 ]
  [0.03164735 0.76564921 0.1688908  0.84831511 0.82541834]
  [0.41998165 0.91077937 0.39302008 0.58494639 0.53296243]]

 [[0.15831626 0.4318825  0.39409235 0.26933671 0.53536078]
  [0.78581655 0.61291791 0.94427446 0.91823292 0.62201185]
  [0.17834568 0.4093826  0.52794081 0.84110649 0.62888985]]]


## 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [10]:
b = np.ones((5,2,3))

## 6. Print b.

In [11]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 7. Do a and b have the same size? How do you prove that in Python code?

In [12]:
a.shape == b.shape

False

## 8. Are you able to add a and b? Why or why not?

In [13]:
sum = a+b
print(sum)
#No, you're not. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

## 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [14]:
c = np.transpose(b,(1, 2, 0))
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

## 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [15]:
d = a + c
print(d)
#because a and c have the same dimensions. 
d.shape

[[[1.45308254 1.03322241 1.39584096 1.92154178 1.7553551 ]
  [1.03164735 1.76564921 1.1688908  1.84831511 1.82541834]
  [1.41998165 1.91077937 1.39302008 1.58494639 1.53296243]]

 [[1.15831626 1.4318825  1.39409235 1.26933671 1.53536078]
  [1.78581655 1.61291791 1.94427446 1.91823292 1.62201185]
  [1.17834568 1.4093826  1.52794081 1.84110649 1.62888985]]]


(2, 3, 5)

## 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [38]:
print(a)
print(d)

#In ex. 10. we added the rearranged b (which we called C) to a, so we added 1 to all elements in a. 

[[[0.44851043 0.53114345 0.72146707 0.17839221 0.99526513]
  [0.91200874 0.07112213 0.07579148 0.03359827 0.93930011]
  [0.23488019 0.84315683 0.37897358 0.48605231 0.02168351]]

 [[0.04468883 0.75790605 0.3922422  0.1401231  0.68846119]
  [0.21098311 0.39951859 0.67757137 0.88959648 0.27873042]
  [0.23723901 0.75653616 0.11935778 0.3418078  0.82937851]]]
[[[1.44851043 1.53114345 1.72146707 1.17839221 1.99526513]
  [1.91200874 1.07112213 1.07579148 1.03359827 1.93930011]
  [1.23488019 1.84315683 1.37897358 1.48605231 1.02168351]]

 [[1.04468883 1.75790605 1.3922422  1.1401231  1.68846119]
  [1.21098311 1.39951859 1.67757137 1.88959648 1.27873042]
  [1.23723901 1.75653616 1.11935778 1.3418078  1.82937851]]]


## 12. Multiply a and c. Assign the result to e.

In [39]:
e = a * c
print(e)

[[[0.44851043 0.53114345 0.72146707 0.17839221 0.99526513]
  [0.91200874 0.07112213 0.07579148 0.03359827 0.93930011]
  [0.23488019 0.84315683 0.37897358 0.48605231 0.02168351]]

 [[0.04468883 0.75790605 0.3922422  0.1401231  0.68846119]
  [0.21098311 0.39951859 0.67757137 0.88959648 0.27873042]
  [0.23723901 0.75653616 0.11935778 0.3418078  0.82937851]]]


## 13. Does e equal to a? Why or why not?

In [40]:
#yes, it does. Because you are multiplying all values in a by 1. 

## 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [61]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9952651317222112
1.0216835069902954
1.4545162021754139


## 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [85]:
f= np.empty([2,3,5])
print(f)



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [84]:

for i in d
     if d_mean > i and i > d_min:
        f[] = 25
    elif d_mean< i and i <d_max:
        f[] =75
    elif i == d_mean:
        f[] == 50
    elif i == d_min:
        f[] ==0
    elif i == d_max:
        f[] ==100

print(d)
print(f)    

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)